version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "miDebug"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-mx9861lv18es"
s3_prefix = "miDebug"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
